using System.Configuration;
using TournamentTrackerLibrary.Models;

namespace TournamentTrackerLibrary.DataAccess.TextFileHelpers
{
    public static class TextFileConnectorProcessor
    {
        /// <summary>
        /// Connects the storage directory from <see cref="AppSettings"/> 
        /// to the specified file name
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns></returns>
        public static string FullFilePath(this string fileName)
            => $@"{ConfigurationManager.AppSettings["textFilesDirectory"]}\{fileName}";

        /// <summary>
        /// Loads file contents into a <see cref="List{string}"/> of <see cref="string"/>.
        /// Invoked on a full file path
        /// </summary>
        /// <param name="filePath">Absolute full file path</param>
        /// <returns><see cref="List{T}"/> of <see cref="string"/>: lines in the file</returns>
        public static List<string> LoadFile(this string filePath)
        {
            if (!File.Exists(filePath))
            {
                return new List<string>();
            }

            return File.ReadAllLines(filePath).ToList();
        }

        public static List<PrizeModel> ConvertToPrizeModels(this List<string> lines)
        {
            var prizes = new List<PrizeModel>();

            foreach (string line in lines)
            {
                string[] cols = line.Split(',');

                // here we do not use the `fail tolerant constructor` 
                // because we do not want to have a half ass built model
                // alternatively, we want this method to crash when something happens
                // this is due to the fact that we read from a file that is generated by
                // the app, so we do expect the data to be right, the opposite is an Exception!
                var p = new PrizeModel();

                p.Id = int.Parse(cols[0]);
                p.PlaceNumber = int.Parse(cols[1]);
                p.PlaceName = cols[2];
                p.PrizeAmount = decimal.Parse(cols[3]);
                p.PrizePercentage = int.Parse(cols[4]);

                prizes.Add(p);
            }

            return prizes;
        }

        public static void SaveToPrizeModelFile(this List<PrizeModel> models, string fileName)
        {
            List<string> lines = new List<string>();

            foreach (PrizeModel p in models)
            {
                lines.Add($"{p.Id},{p.PlaceNumber},{p.PlaceName},{p.PrizeAmount},{p.PrizePercentage}");
            }

            File.WriteAllLines(fileName.FullFilePath(), lines);
        }
    }
}
